/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conexaobd;

import conexaobd.DAO.DiretorDAO;
import conexaobd.DAO.FilmeDAO;
import conexaobd.DAO.IngressoDAO;
import conexaobd.DAO.PessoaDAO;
import conexaobd.model.Diretor;
import conexaobd.model.Filme;
import conexaobd.model.Ingresso;
import conexaobd.model.Pessoa;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AVRJR
 */
public class Listar extends javax.swing.JFrame {

    DefaultListModel dlmDiretor = new DefaultListModel();
    DefaultListModel dlmFilme = new DefaultListModel();
    DefaultListModel dlmIngresso = new DefaultListModel();
    DefaultListModel dlmPessoa = new DefaultListModel();
    
    ArrayList<Diretor> diretores = new ArrayList();
    ArrayList<Filme> filmes = new ArrayList();
    ArrayList<Ingresso> ingressos = new ArrayList();
    ArrayList<Pessoa> pessoas = new ArrayList();
    
    
   
    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        listaVoltar = new javax.swing.JButton();
        listaListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaFilme = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDiretor = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaPessoa = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaIngresso = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listagem do Banco de Dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Diretor:");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setText("Filme:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Ingresso:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setText("Pessoa:");

        listaVoltar.setText("VOLTAR");
        listaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVoltarActionPerformed(evt);
            }
        });

        listaListar.setText("LISTAR");
        listaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaListarActionPerformed(evt);
            }
        });

        listaFilme.setModel(dlmFilme);
        jScrollPane1.setViewportView(listaFilme);

        listaDiretor.setModel(dlmDiretor);
        jScrollPane3.setViewportView(listaDiretor);

        listaPessoa.setModel(dlmPessoa);
        jScrollPane4.setViewportView(listaPessoa);

        listaIngresso.setModel(dlmIngresso);
        jScrollPane5.setViewportView(listaIngresso);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(listaListar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(listaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaListar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVoltarActionPerformed
        // TODO add your handling code here:
        
        TelaInicial t2 = new TelaInicial();
        t2.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_listaVoltarActionPerformed

    private void listaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaListarActionPerformed
        // TODO add your handling code here:
        
        
        
        DiretorDAO dd1 = new DiretorDAO();
        FilmeDAO fd1 = new FilmeDAO();
        IngressoDAO id1 = new IngressoDAO();
        PessoaDAO pd1 = new PessoaDAO();
        
        dlmDiretor.clear();
        diretores = dd1.buscarDiretoresSemFiltro();
        
        dlmFilme.clear();
        filmes = fd1.buscarFilmesSemFiltro();
        
        dlmIngresso.clear();
        ingressos = id1.buscarIngressosSemFiltro();
        
        dlmPessoa.clear();
        pessoas = pd1.buscarPessoasSemFiltro();
        
        for( int i = 0 ; i < diretores.size() ; i++ ){
            dlmDiretor.addElement("CPF: " + diretores.get(i).getCpf());
            dlmDiretor.addElement("Nome: " + diretores.get(i).getNome());
            dlmDiretor.addElement("Idade: " + diretores.get(i).getIdade());
            dlmDiretor.addElement("-------------------------------------");
        }
        
         for( int i = 0 ; i < filmes.size() ; i++ ){
            dlmFilme.addElement("idFilme: " + filmes.get(i).getIdFilme());
            dlmFilme.addElement("Nome: " + filmes.get(i).getNome());
            dlmFilme.addElement("Gênero: " + filmes.get(i).getGenero());
            dlmFilme.addElement("-------------------------------------");
        }
        
         for( int i = 0 ; i < ingressos.size() ; i++ ){
            dlmIngresso.addElement("CPF: " + ingressos.get(i).getCodigo());
            dlmIngresso.addElement("Valor: " + ingressos.get(i).getValor());
            dlmIngresso.addElement("Poltrona: " + ingressos.get(i).getPoltrona());
            dlmIngresso.addElement("-------------------------------------");
        }
        
         for( int i = 0 ; i < pessoas.size() ; i++ ){
            dlmPessoa.addElement("RG: " + pessoas.get(i).getRg());
            dlmPessoa.addElement("Valor: " + pessoas.get(i).getNome());
            dlmPessoa.addElement("Poltrona: " + pessoas.get(i).getIdade());
            dlmPessoa.addElement("-------------------------------------");
        }
         
    }//GEN-LAST:event_listaListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listaDiretor;
    private javax.swing.JList<String> listaFilme;
    private javax.swing.JList<String> listaIngresso;
    private javax.swing.JButton listaListar;
    private javax.swing.JList<String> listaPessoa;
    private javax.swing.JButton listaVoltar;
    // End of variables declaration//GEN-END:variables
}
